title: African Terminal
email: admin@africanterminal.com
description: >
  TODO (will appear in your document head meta (for
  Google search results) and in your feed.xml site description)
# baseurl: "" # the subpath of the site, e.g. /blog
# url: "http://gspgaznwpw894aefacpe7tb94.zelpst.de"
# twitter_username:
# github_username:

# Build settings
markdown: kramdown
# theme: minima # default theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:categories/:title/

menus:
  main:
    - Handel
    - Events
    - Business School
  about:
    - Die Kooperative
    - Ort
    - Vision
